### ISSUE TITLE
What's with all this licensing stuff?

### ISSUE THREAD

**Issue by flarn2006** [jugglingcats/XEditNet#1]
Just wondering. Did this program use to be proprietary or something? Cause I don't really see the point of all that code in an open-source program.

**Comment by jugglingcats** [comment]
Yes, originally I planned to sell this app. Thanks for your interest. This project is up on github more for posterity than any other reason. It's old, unfinished and no longer active...

**Comment by flarn2006** [comment]
Ok, well kudos for going open source regardless! :+1:
